sm components to use C++11 standard
This commit does not have any functional or performance change.
This change adds -std=c++11 compile option to Makefiles to
enalbe using C++11 standard features.
This change also cleans errors that c++11 standard complains:
Werror=literal-suffix,
e.g:
   "msg_seq=%"PRIi64"."
   error: invalid suffix on literal;
          C++11 requires a space between literal and identifier
changed to:
   "msg_seq=%" PRIi64 "."

Story: 2003493
Task: 24770

Change-Id: I0225a4326ff8320f36246cc5678698781e903617
Signed-off-by: Bin Qian <bin.qian@windriver.com>